version: '3.8'

services:

  dev_app:
    image: pet:dev
    container_name: dev_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      dev_db:
        condition: service_healthy
    links:
      - dev_db
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://dev_db:5432/pet
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PARENT_DIRECTORY: /
      APP_PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ${HOST_PARENT_DIRECTORY}:/pet

  dev_db:
    image: postgres
    container_name: dev_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: pet
    ports:
      - "${EXTERNAL_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d pet" ]
      interval: 8s
      timeout: 4s
      retries: 4